version: "3.7"

services: 
  php:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - INSTALL_OPCACHE=${INSTALL_OPCACHE}
        - PHP_VERSION=${PHP_VERSION}
    tty: true
    volumes: 
      - .:/var/www/